### ISSUE TITLE
[BUG] Draggable UI elements are broken when using ScaleMode::Percent

### ISSUE THREAD

**Issue by bonsairobo** [amethyst/amethyst#2095]
## Description

When using `percent: true` on my `UiTransformData` in the `UiFormat` prefab, the widget moves on dragging, but it moves incorrectly, presumably because the `percent: true` causes some bad scaling behavior.

## Reproduction Steps

1. Edit the ui example to make the "Draggable Button" have "percent: true"
2. Fix the x, y, width, height to make sure the button is still a reasonable size and position
3. Run the example and try to drag the button

## What You Expected to Happen

The button stays under my cursor while dragging.

## What Actually Happened

The button flew off the screen.

## Your Environment

1. Mac OS
2. 10.14.6 (18G1012)
3. rev 8c022f464e3d17a4b997cad83c5a1a62c7289ace

**Comment by MegasKomnenos** [comment]
I just fixed it on my fork. Will make a PR.

**Comment by mrhatman** [comment]
This has been fixed,  and can be closed

**Comment by bonsairobo** [comment]
I don't think it's fixed. I'm running with the new patch and experiencing the same problem.

Looking at the code, I don't think it accounts for multiple levels of `ScaleMode::Percent` in a hierarchy. For this to really work, you need to rescale until you reach the root or a parent that's not `ScaleMode::Percent`.

```
let change = mouse_pos - *prev;

let mut scale_x = 1.0;
let mut scale_y = 1.0;
let mut cur_level_entity = Some(*entity);
loop {
    if let Some(entity) = cur_level_entity.take() {
        match ui_transforms.get(entity).unwrap().scale_mode {
            ScaleMode::Pixel => { break; }
            ScaleMode::Percent => {
                let mut parent_width = screen_dimensions.width();
                let mut parent_height = screen_dimensions.height();

                if let Some(parent) = hierarchy.parent(entity) {
                    if let Some(ui_transform) = ui_transforms.get(parent) {
                        parent_width = ui_transform.width;
                        parent_height = ui_transform.height;
                    }

                    cur_level_entity = Some(parent);
                }

                scale_x /= parent_width;
                scale_y /= parent_height;
            }
        }
    } else {
        break;
    }
}

let ui_transform = ui_transforms.get_mut(*entity).unwrap();
ui_transform.local_x += scale_x * change[0];
ui_transform.local_y += scale_y * change[1];
```

**Comment by bonsairobo** [comment]
I have a better factoring of this code I can submit for a PR.

**Comment by bonsairobo** [comment]
This is fixed :)

I also recently realized that you can just get the parent's pixel_width and pixel_height instead of traversing all the way up the hierarchy, so I'm making a PR for that simplification.
